### ISSUE TITLE
Exception in EditTablePage.Json.cs

### ISSUE THREAD

**Issue by atifwaqar** [Smorgasbord-Development/DatabaseEditor#1]
I'm just debugging your code and i get an exception on this line, any idea what is the cause?

![image](https://cloud.githubusercontent.com/assets/4388707/19482699/24480546-9552-11e6-8525-337ef3b98cc6.png)

In my opinion this exception occurs if we have a Get constructor in DB Class. 
This is how my code looks like : 

![image](https://cloud.githubusercontent.com/assets/4388707/19482846/980ac4fa-9552-11e6-95de-0512b7803e3f.png)

**Comment by andwah** [comment]
Probably that the property name in your class has the same name as a property in the json bound object.

I will take a look after work. thanks reporting it.

**Comment by andwah** [comment]
btw the problem is not in your class.. it's in my code.. i should find a way around this thing.

**Comment by atifwaqar** [comment]
Got it. Thanks :)

**Comment by andwah** [comment]
i release a new version 1.0.13.0.   i hope it will fix this issue.
